import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import YAML from 'yaml';
import { loadAndValidate } from '../src/validate.js';
import { renderWorkflow } from '../src/renderers/index.js';
import { renderFrontmatter } from '../src/renderers/shared.js';

describe('renderers', () => {
  it('matches exact golden files for every default target', () => {
    const { workflow } = loadAndValidate('examples/code-change-verification.workflow.yaml');
    const files = renderWorkflow(workflow!, 'examples/code-change-verification.workflow.yaml');
    for (const file of files) {
      const expected = readFileSync(`test/fixtures/expected/${file.path}`, 'utf8');
      expect(file.content, file.path).toBe(expected);
    }
    expect(files.map(f => f.path).sort()).toEqual([
      '.agents/skills/code-change-verification/SKILL.md',
      '.claude/skills/code-change-verification/SKILL.md',
      '.cursor/rules/code-change-verification.mdc',
      '.github/instructions/code-change-verification.instructions.md',
      'AGENTS.md',
    ].sort());
  });

  it('puts frontmatter before generated notices', () => {
    const { workflow } = loadAndValidate('examples/code-change-verification.workflow.yaml');
    for (const file of renderWorkflow(workflow!, 'examples/code-change-verification.workflow.yaml').filter(f => f.path !== 'AGENTS.md')) {
      expect(file.content.startsWith('---\n'), file.path).toBe(true);
      expect(file.content.indexOf('---')).toBeLessThan(file.content.indexOf('Generated by skillforge'));
    }
  });

  it('serializes YAML-sensitive frontmatter safely', () => {
    const fm = renderFrontmatter({ description: 'colon: text quotes "like this" apostrophe\'s brackets [x] hash # text multi word strings' });
    const data = YAML.parse(fm.replace(/^---\n/, '').replace(/\n---\n$/, ''));
    expect(data.description).toContain('colon: text');
    expect(data.description).toContain('hash # text');
  });
});
