import path from 'node:path';
import type { Diagnostic } from '../diagnostics.js';
import { normalizeWorkflow, type NormalizedWorkflow } from '../normalize.js';
import { validateSchema } from '../schema.js';

export function kebab(s: string): string { return (s || 'imported-workflow').replace(/([a-z0-9])([A-Z])/g,'$1-$2').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'') || 'imported-workflow'; }
export function titleCase(id: string): string { return id.split('-').map(x=>x ? x[0].toUpperCase()+x.slice(1) : x).join(' '); }
export function asString(v: unknown): string|undefined { return typeof v === 'string' && v.trim() ? v : undefined; }
export function asStrings(v: unknown): string[] { if (Array.isArray(v)) return v.filter(x=>typeof x==='string'); if (typeof v==='string' && v.trim()) return v.split(',').map(x=>x.trim()).filter(Boolean); return []; }
export function firstH1(body: string): string|undefined { return body.split(/\r?\n/).map(l=>l.match(/^#\s+(.+)$/)?.[1]?.trim()).find(Boolean); }
export function firstParagraph(body: string): string|undefined { return body.split(/\n\s*\n/).map(p=>p.replace(/^#+\s+/gm,'').trim()).find(p=>p && !p.includes('Generated by skillforge')); }
export function extractSteps(body: string): string[] { const lines = body.split(/\r?\n/); const out:string[]=[]; for (const l of lines) { const m = l.match(/^\s*(?:[-*+] |\d+[.)]\s+)(.+)$/); if (m && !m[1].includes('Generated by skillforge')) out.push(m[1].trim()); } return out; }
export function buildWorkflow(raw: any, diagnostics: Diagnostic[]): { workflow: NormalizedWorkflow; diagnostics: Diagnostic[] } {
  const s = validateSchema(raw); diagnostics.push(...s.diagnostics); if (!s.workflow) throw new Error('Imported workflow did not validate.'); return { workflow: normalizeWorkflow(s.workflow), diagnostics };
}
export function mdWorkflow(id:string, fm:Record<string,unknown>, body:string, sourceTarget:string, extra:any={}, diagnostics:Diagnostic[]=[]): {workflow: NormalizedWorkflow; diagnostics: Diagnostic[]} {
  const orig = id; id = kebab(id);
  if (orig !== id) diagnostics.push({severity:'warning', path:'import.idNormalized', message:`Source id "${orig}" was normalized to "${id}".`});
  const title = firstH1(body) ?? titleCase(id);
  const description = asString(fm.description) ?? asString(fm.name) ?? firstParagraph(body)?.split(/[.!?]\s/)[0] ?? `Imported from ${sourceTarget}`;
  let steps = extractSteps(body);
  if (!steps.length) { const p = firstParagraph(body); if (p && p !== title) steps = [p]; }
  if (!steps.length) { steps = [`Follow the imported ${sourceTarget} instructions from the source artifact.`]; diagnostics.push({severity:'warning', path:'import.lowStructure', message:'Source artifact did not contain clear workflow sections. Imported workflow uses conservative fallback steps.'}); }
  return buildWorkflow({ id, title, description, version:'0.1.0', triggers:{ phrases: asStrings(fm.when_to_use), globs: asStrings(fm.globs), manual:false, ...extra.triggers }, scope:{ paths: asStrings(fm.paths), ...extra.scope }, workflow:{ goal: description, steps }, commands:{}, safety:{ allowedTools: asStrings(fm['allowed-tools']), never:[] }, outputs:{ successCriteria:[] }, targets:{ [sourceTarget]: { enabled:true }, ...extra.targets } }, diagnostics);
}
export function idFromFile(p:string){ return kebab(path.basename(p).replace(/\.instructions\.md$|\.mdc$|\.md$/,'')); }
