import { existsSync, writeFileSync } from 'node:fs';
import YAML from 'yaml';
import { formatDiagnostics, hasErrors } from '../diagnostics.js';
import { importArtifact } from '../importers/index.js';
import type { SourceFormat } from '../importers/types.js';
import { validateSchema } from '../schema.js';
export async function runImportCommand(args:{source:string; from?:SourceFormat; out?:string; id?:string; force?:boolean}) { const r=importArtifact(args.source,{from:args.from,id:args.id}); const raw:any={...r.workflow}; const y=YAML.stringify(raw,{sortMapEntries:false,lineWidth:0}); const content=`# Generated by skillforge import from ${args.source}.\n# Review semantic-loss warnings before using this as source of truth.\n${y}`; const v=validateSchema(YAML.parse(y)); const diags=[...r.diagnostics,...v.diagnostics]; if (hasErrors(diags)) return {code:1,stdout:'',stderr:formatDiagnostics(diags)}; if (!args.out) return {code:0,stdout:`${formatDiagnostics(diags)}\n${content}`,stderr:''}; if (existsSync(args.out) && !args.force) return {code:1,stdout:'',stderr:`error file.exists:\n  Refusing to overwrite existing file: ${args.out}. Pass --force to overwrite.`}; writeFileSync(args.out,content,'utf8'); return {code:0,stdout:`${formatDiagnostics(diags)}\nWrote ${args.out}`,stderr:''}; }
