import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { GeneratedFile } from './renderers/shared.js';

export function isSafeGenerated(content: string) {
  return content.includes('Generated by skillforge') || content.includes('skillforge:');
}

export function materialize(file: GeneratedFile, base: string, force = false): { path: string; content: string; changed: boolean } {
  const p = join(base, file.path);
  let content = file.content;
  if (file.path === 'AGENTS.md' && existsSync(p)) {
    const old = readFileSync(p, 'utf8');
    const m = content.match(/<!-- skillforge:(.+) BEGIN -->/);
    const id = m?.[1];
    if (id) {
      const re = new RegExp(`<!-- skillforge:${id} BEGIN -->[\\s\\S]*?<!-- skillforge:${id} END -->\\n?`);
      content = re.test(old) ? old.replace(re, content) : `${old}${old.endsWith('\n') ? '' : '\n'}\n${content}`;
    }
  }
  const old = existsSync(p) ? readFileSync(p, 'utf8') : undefined;
  if (old !== undefined && old !== content && file.path !== 'AGENTS.md' && !force && !isSafeGenerated(old)) {
    throw new Error(`error file.unmanaged:\n  Refusing to overwrite unmanaged file: ${file.path}. Pass --force to overwrite.`);
  }
  return { path: p, content, changed: old !== content };
}

export function writeGenerated(files: GeneratedFile[], base: string, force = false) {
  const written: string[] = [];
  for (const f of files) {
    const m = materialize(f, base, force);
    mkdirSync(dirname(m.path), { recursive: true });
    writeFileSync(m.path, m.content, 'utf8');
    written.push(f.path);
  }
  return written;
}

export function diffGenerated(files: GeneratedFile[], base: string) {
  return files.map(f => {
    const m = materialize(f, base, true);
    const exists = existsSync(m.path);
    const old = exists ? readFileSync(m.path, 'utf8') : '';
    if (old === m.content) return `=== ${f.path} up to date ===`;
    const state = exists ? 'changed' : 'created';
    const before = exists ? old.split('\n').slice(0, 8).map(l => `- ${l}`).join('\n') : '- <missing>';
    const after = m.content.split('\n').slice(0, 12).map(l => `+ ${l}`).join('\n');
    return `=== ${f.path} ${state} ===\n--- before\n${before}\n+++ after\n${after}`;
  }).join('\n\n');
}

export function checkGenerated(files: GeneratedFile[], base: string) {
  const stale: string[] = [];
  for (const f of files) {
    const m = materialize(f, base, true);
    if (!existsSync(m.path)) stale.push(`missing: ${f.path}`);
    else if (readFileSync(m.path, 'utf8') !== m.content) stale.push(`stale: ${f.path}`);
  }
  return stale;
}
